project_id = "pjpickbfzrlhdnggzgcd"

[functions.launch-token]
verify_jwt = true

[functions.process-airdrop]
verify_jwt = true

[functions.process-scheduled-airdrops-cron]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.verify-token]
verify_jwt = true