project_id = "pjpickbfzrlhdnggzgcd"

[functions.launch-token]
verify_jwt = true

[functions.process-airdrop]
verify_jwt = true

[functions.process-scheduled-airdrops-cron]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.verify-token]
verify_jwt = true

[functions.api-gateway]
verify_jwt = false

[functions.track-referral]
verify_jwt = false

[functions.create-merkle-airdrop]
verify_jwt = true

[functions.ai-market-analysis]
verify_jwt = true

[functions.grok-chat]
verify_jwt = true

[functions.aura-timp]
verify_jwt = true