// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjpickbfzrlhdnggzgcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcGlja2JmenJsaGRuZ2d6Z2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTQyOTYsImV4cCI6MjA2Nzg3MDI5Nn0.sw60t56-ARy9K58r0CS7E5y95lC9il5PUGVAPYWMQ8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});